import pc2d from  "./core/pc2d-core.js";
import  "./core/pc2d-eventhandle.js";
import  "./core/pc2d-tags.js";
import  "./math/math.js";
import  "./math/curve.js";
import  "./math/curve-set.js";
import  "./math/curve-evaluator.js";
import  "./math/vec2.js";
import  "./math/vec3.js";
import  "./math/vec4.js";
//import  "./math/quat.js";
// import  "./math/mat3.js";
// import  "./math/mat4.js";
import  "./framework/utils/sorted-loop-array.js";
import  "./framework/components/data.js";
import  "./framework/components/component.js";
import  "./framework/components/system.js";
import  "./framework/components/register.js";
import  "./framework/components/script/data.js";
import  "./framework/components/script/component.js";
import  "./framework/components/script/system.js";
import  "./framework/components/css/data.js";
import  "./framework/components/css/component.js";
import  "./framework/components/css/system.js";
// import  "./framework/components/animation/data.js";
// import  "./framework/components/animation/component.js";
// import  "./framework/components/animation/system.js";
import  "./pc2d-graphnode-web.js";
import  "./net/http.js";
import  "./script/script.js";
import  "./script/script-type.js";
import  "./script/script-attributes.js";
import  "./script/script-registry.js";
import  "./script/script.js";
import  "./asset/asset-list-loader.js";
import  "./asset/asset-variant.js";
import  "./asset/asset.js";
import  "./asset/asset-registry.js";
import  "./resources/loader.js";
import  "./resources/script.js";
import  "./resources/parser/scene-web.js";
import  "./resources/scene.js";
import  "./resources/css.js";
import  "./resources/json.js";
import  "./resources/template.js";
import  "./template/template-utils.js";
import  "./template/template.js";
import  "./graphics/device.js";
import  "./framework/pc2d-entity.js";
import  "./framework/pc2d-script.js";
import  "./framework/pc2d-scene-registry.js";
import  "./framework/pc2d-application.js";

export default pc2d;

